// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_KV: KVNamespace;
	MY_QUEUE_WORKER_BASE_URL: string;
	DATABASE: D1Database;
	MY_QUEUE: Queue;
}
